### ISSUE TITLE
URLs with hash

### ISSUE THREAD

**Issue by teekey99** [nittro/nittro#13] opened 2017-05-12 12:00 UTC
How should I handle hashes in URLs properly? Every time a hash appends to the URL (e. g. after simple click on an anchor) all Nittro services stop working and I have to reload the page otherwise all forms etc. are not handled via AJAX. I guess the Nittro router is not able to resolve the "new" URL with hash. I am using whitelist option for all links, so only those with data-ajax="true" should be handled by Nittro AJAX.

**Comment by jahudka** [comment] 2017-05-12 12:04
That's weird - you shouldn't need to treat URLs with hashes any differently than normal URLs - Nittro should automatically decide if it should do anything based on which part of the URL changes. I assume you're using the latest Nittro 2.0.*, is that correct?

**Comment by teekey99** [comment] 2017-05-12 12:10
Yes, i am currently on 2.0.4. I also think it's weird, but it really happens every time a hash appends to any URL on the site. Most of all AJAX forms are not submitted via AJAX then but the page redirects as a standard non-AJAX request.

**Comment by jahudka** [comment] 2017-05-12 12:35
Okay, I'm starting to think I know where the issue lies. Let me check and
get back to you in a couple of hours (I'm on the road right now).

**Comment by teekey99** [comment] 2017-05-12 13:44
No problem, it's not a critical issue right now. Thank you very much!

**Comment by jahudka** [comment] 2017-05-12 16:41
Okay, try updating to v2.0.5 :-)

The issue was that Nittro ignores any URL which changes in hash only (so as not to interfere with anchors etc.) - but that's obviously wrong for form submissions. The updated version doesn't check for hash change when forms are submitted.

**Comment by teekey99** [comment] 2017-05-16 09:15
I apologize for such late response. Today, I updated as you suggested, but the issue still remains.

**Comment by teekey99** [comment] 2017-05-19 15:19
@jahudka Can you please re-open the issue? Thank you.

**Comment by jahudka** [comment] 2017-05-19 15:54
@teekey99 sorry, reopening now, but I can't reproduce it anymore - I only just noticed that I didn't update the pre-built packages after publishing the fix, so if you're using one of those, please try updating once again - of course if you're building Nittro yourself using Gulp or Grunt or if you used the online builder at the Nittro download site you would already have the latest package, so the problem would be elsewhere.

**Comment by teekey99** [comment] 2017-05-19 20:07
Thanks! I am building Nittro myself. I will try to find out what am I doing wrong. Anyway, I did just a short test with removing `checkUrl` method from the condition in `_handleSubmit` method (where you did the last update according to b30b0ea361341d4beb1c29a21fd31f83b7cc2cb9) and then all form submissions work. I will try to examine more where's the catch with my project and let you know then.

**Comment by jahudka** [comment] 2017-05-20 16:23
Hmm, okay, and could you please check and post here the relevant methods
from your package? Specifically what the checkUrl method looks like and how
it was called from _handleSubmit before your modification. If you built
your package with source maps, then the best way to see the *actual* code
in the package would be to examine the source files using a browser's
development console.

The issue may be related to how npm handles multiple package versions -
it's possible that when you updated the packages, the old ones were kept
alongside the new ones which would then probably appear as "subpackages"
somewhere like node_modules/nittro/node_modules/nittro-forms and such. The
builder may have some issues locating the correct source package when that
happens. The solution would be to rm -rf node_modules && npm install from
scratch.

**Comment by teekey99** [comment] 2017-05-20 21:48
@jahudka Awesome! How simple :D Re-installing node modules did work indeed! Thank you so much!

**Comment by teekey99** [comment] 2017-05-20 21:50
@jahudka BTW great work with Nittro! I am using it on my first project now, still learning how to use it properly but you've done a remarkable job!

**Comment by jahudka** [comment] 2017-05-20 23:10
@teekey99 thanks for the praise! I'm glad someone is finding it useful. Sorry about the complications, I've known about the npm issue for a while and I've taken steps to resolve it, but apparently it's still broken.. I'll look into it and try to come up with a permanent solution. I'm closing this one though because the bug you reported originally is indeed fixed now.

**Closed by jahudka** 2017-05-20 23:10 UTC
Labels: bug
